# This is a basic workflow to help you get started with Actions

name: mainDeployToProd

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 deployToProd:
    runs-on: ubuntu-latest
    steps:
      - name: "Run deploy on server"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            sudo docker pull daniel0k/angular:prod_latests
            docker stop prod_latest_container
            docker rm prod_latest_container
            sudo docker run --name=prod_latest_container -d -p 81:80 daniel0k/angular:prod_latests
